name: Docker Build and Push

on:
  push:
    branches:
      - main  # You can change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x  # Use the latest available .NET Core version

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: daikmasa
        password: 7LL@iArX?wpb6!;

    - name: Build Docker image
      run: docker compose up
      
    - name: Tag Docker image
      run: docker tag compare:latest daikmasa/compare:latest

    - name: Push Docker image to Docker Hub
      run: docker push daikmasa/compare:latest
